name: Actualizador Demoscópico Diario

on:
  schedule:
    # Se ejecuta todos los días a las 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Nos permite poner un botón manual por si quieres forzarlo

jobs:
  simular_datos:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Da permiso al robot para sobreescribir el JSON

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías de Scraping
        run: pip install pandas requests lxml html5lib

      - name: Despertar al Robot
        run: python actualizar_datos.py

      - name: Guardar los nuevos datos en GitHub
        run: |
          git config user.name "Robot Demoscópico"
          git config user.email "robot@simulador.local"
          git add datos_encuestas.json
          # Si no hay cambios, que no dé error
          git commit -m "🤖 Actualización diaria de encuestas" || exit 0
          git push
